language: go
go:
  - 1.8.x
before_install:
  - mv $HOME/gopath/src/github.com/Teamwork $HOME/gopath/src/github.com/teamwork
script:
  - cd $HOME/gopath/src/github.com/teamwork/tnef
  - ./bin/test
  - ./bin/coverage
  - ./bin/lint
